site_name: "ARCN - Hands on Labs"
site_author: "Iván Sanchez"
theme:
  name: "material"
nav:
  - Home: index.md
  - SOLID: solid.md
  - TDD: tdd.md
  - Quiz XP: quizXP.md
extra_css:
  - assets/quiz_xp.html