site_name: "ARCN - Hands on Labs"
site_author: "Iván Sanchez"
theme:
  name: "material"
nav:
  - Home: index.md
  - SOLID: solid.md
  - TDD: tdd.md
  - BDD Parte 1: bdd-part1.md
  - BDD Parte 2: bdd-part2.md
  - DDD: ddd.md
  - Microservice Basics: microservice-basics.md
  - Event driven lab: event-driven-lab.md

plugins:
  - search
  - mermaid2

